version: 2
jobs:
  build:
    docker:
      - image: 'cimg/node:14.19'
    steps:
      - 'checkout'
      - restore_cache:
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
      - run: 'corepack yarn install --immutable'
      - save_cache:
          key: 'yarn-packages-{{ checksum "yarn.lock" }}'
          paths:
            - '.yarn/cache'
      - run: 'corepack yarn ci'
